sonar.projectKey=python-project-83
sonar.projectName=python-project-83
sonar.projectVersion=1.0

sonar.sources=page_analyzer

sonar.cpd.exclusions=page_analyzer/templates/*.html

sonar.exclusions=page_analyzer/templates/**/*.html
